[[profiles]]
name = "Mac"
synced_files = [
    ".config/aerospace/aerospace.toml",
    ".config/alacritty",
    ".config/amp/settings.json",
    ".config/borders/bordersrc",
    ".config/ghostty/config",
    ".config/helix",
    ".config/kitty",
    ".config/nvim",
    ".config/qmd",
    ".config/sesh",
    ".config/starship.toml",
    ".config/wezterm",
    ".config/zellij",
]
packages = []
